modLoader="javafml" #mandatory

loaderVersion="${loader_version_range}" #mandatory

license="${mod_license}"

[[mods]] #mandatory

modId="${mod_id}" #mandatory

version="${mod_version}" #mandatory

displayName="${mod_name}" #mandatory

authors="${mod_authors}"

description='''
服务器RiaFST的核心模组
一点点混沌，很多的乐趣
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]] #optional
    modId="forge" #mandatory
    type="required" #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create"
    type="required"
    versionRange="[6.0,6.1)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="farmersdelight"
    type="required"
    versionRange="[1.2.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="kitchenkarrot"
    type="required"
    versionRange="[1.20.1-0.6.4b,)"
    ordering="NONE"
    side="BOTH"